import {publicSnapshot,sha256,canonical,fileInfo} from '../../public/bad/model.mjs';
import {verifyFiles,verifyAttachment,stampDeclarations,sanitizeDraft,assertPublish} from './validation.mjs';
import {HttpError} from '../validation.mjs';
export async function runBad(op,args,actor,{rpc,randomToken,hash,origin}){
 if(op==='bad_read')return rpc(op,null,args);
 if(op==='bad_worker_get'||op==='bad_contribute'){const token_hash=await hash(args.token);delete args.token;args.token_hash=token_hash;if(args.contribution?.file)args.contribution.file=await verifyAttachment(args.contribution.file,true);return rpc(op,null,args);}
 if(op==='bad_staff_create'){const token=randomToken();const result=await rpc(op,actor,{...args,token_hash:await hash(token)});return {...result,access_url:origin+'/bad-site.html#'+token};}
 if(op==='bad_save'){const current=await rpc('bad_get',actor,{id:args.id});if(current.version!==args.version)throw new HttpError(409,'Es gibt einen neueren Stand. Bitte Ihre Eingaben sichern und das Projekt neu öffnen.');const draft=await verifyFiles(args.draft);for(const v of draft.document_versions){const prev=current.draft?.document_versions.find(x=>x.id===v.id);if(prev&&canonical([prev.url,prev.text,prev.document_date,prev.source_kind,prev.source_label,prev.file?.sha256])!==canonical([v.url,v.text,v.document_date,v.source_kind,v.source_label,v.file?.sha256]))for(const group of ['document_links','care','maintenance'])for(const b of draft[group])if((b.version_id||b.source_version_id)===v.id)b.confirmation=null;}stampDeclarations(draft,current.draft,actor,new Date().toISOString());return rpc(op,actor,{...args,draft});}
 if(op==='bad_publish'){const current=await rpc('bad_get',actor,{id:args.id});const duplicate=current.releases.find(r=>r.request_id===args.request_id);if(duplicate)return {release:duplicate,version:current.version};if(current.version!==args.version)throw new HttpError(409,'Es gibt einen neueren Stand. Bitte erneut prüfen.');const draft=await verifyFiles(sanitizeDraft(current.draft));assertPublish(draft,current.latest?.snapshot);const snapshot=publicSnapshot(draft,current.company,{number:current.releases.length+1,at:new Date().toISOString(),by:actor,pass_number:current.pass_number,supersedes:current.latest?.id||''});return rpc(op,actor,{...args,snapshot,sha256:await sha256(canonical(snapshot))});}
 return rpc(op,actor,args);
}
