import {jpegInfo,validateStaticPDF} from '../../public/bad/file-check.mjs';
import {SCHEMA,MAX_PHOTOS,MAX_ARCHIVED_BYTES,roles,areaTypes,photoSteps,scopeTypes,documentTypes,productKeys,colorKeys,pick,usageBasis,bindingBasis,used,careValid,clone,canonical,fileInfo} from '../../public/bad/model.mjs';
import {HttpError,fail,uuid,text,url,version,token} from '../validation.mjs';
const obj=v=>{if(!v||typeof v!=='object'||Array.isArray(v))fail();return v;};
const list=(v,max,fn)=>{if(!Array.isArray(v)||v.length>max)fail('Zu viele oder ungültige Einträge.');return v.map(fn);};
const choice=(v,values)=>{if(!values.includes(v))fail('Ungültige Auswahl: '+String(v).slice(0,30));return v;};
const stringFields=(v,keys,max=1000)=>Object.fromEntries(keys.map(k=>[k,text(v?.[k],max)]));
const date=v=>{v=text(v,10);if(v&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))fail('Bitte ein gültiges Datum wählen.');return v;};
const stamp=v=>{if(!v)return null;obj(v);return {basis:text(v.basis,80),by:text(v.by,120),at:text(v.at,50)};};
const optionalId=v=>v?uuid(v):'';
const ref=v=>({usage_id:uuid(v.usage_id),aspect:choice(v.aspect||'product',['product','color','all'])});
const visibility=v=>v==='public'?'public':'internal';
function file(v,photo=false){if(!v)return null;obj(v);const data=text(v.data,photo?550000:1400000);const valid=photo?/^data:image\/jpeg;base64,\/9j\/[A-Za-z0-9+/]*={0,2}$/:/^data:application\/pdf;base64,JVBER[A-Za-z0-9+/]*={0,2}$/;if(!valid.test(data))fail(photo?'Bitte ein komprimiertes JPEG-Foto verwenden.':'Bitte eine PDF-Datei bis 1 MB verwenden.');return {name:text(v.name,180).replace(/[\x00-\x1f\\/]/g,'_')||(photo?'Foto.jpg':'Dokument.pdf'),data,size:Number.isInteger(v.size)?v.size:0,mime:photo?'image/jpeg':'application/pdf',sha256:/^[a-f0-9]{64}$/.test(v.sha256||'')?v.sha256:''};}
function product(p){obj(p);return {...stringFields(p,productKeys,250),variant_status:choice(p.variant_status||'unknown',['known','unknown'])};}
function bind(v){return {id:uuid(v.id),area_id:uuid(v.area_id),section_id:uuid(v.section_id),dependencies:list(v.dependencies||[],40,ref),confirmation:stamp(v.confirmation)};}
/** Allowlist, limits and referential integrity; no arbitrary nested fields survive. */
export function sanitizeDraft(input){const d=obj(input);if(d.schema!==SCHEMA)fail('Unbekanntes Bad-Datenformat.');const p=obj(d.project);
 const out={schema:SCHEMA,project:{...stringFields(p,['title','customer','address','room','service'],500),completed_on:date(p.completed_on),cover_photo_id:optionalId(p.cover_photo_id),public_address:p.public_address===true},
 areas:list(d.areas,20,a=>({id:uuid(a.id),type:choice(a.type,Object.keys(areaTypes)),trade:choice(a.trade,['tile','seamless']),name:text(a.name,100),expected_photos:[...new Set(list(a.expected_photos||[],8,s=>choice(s,Object.keys(photoSteps))))]})),
 sections:list(d.sections,50,s=>({id:uuid(s.id),kind:choice(s.kind,['initial','repair','maintenance']),performed_from:date(s.performed_from),performed_to:date(s.performed_to),description:text(s.description,1000),area_ids:list(s.area_ids,20,uuid),region_known:s.region_known===true,region:text(s.region,1000)})),
 scopes:list(d.scopes,500,s=>({id:uuid(s.id),area_id:uuid(s.area_id),section_id:uuid(s.section_id),role:choice(s.role,Object.keys(roles)),kind:choice(s.kind,Object.keys(scopeTypes)),company:text(s.company,200),evidence_version_id:optionalId(s.evidence_version_id),note:text(s.note,1000)})),
 uses:list(d.uses,500,u=>({id:uuid(u.id),area_id:uuid(u.area_id),section_id:uuid(u.section_id),role:choice(u.role,Object.keys(roles)),product:product(u.product),spec:stringFields(u.spec,colorKeys,500),rest:{present:choice(u.rest?.present||'unknown',['yes','no','unknown']),...stringFields(u.rest,['quantity','location'],500)},state:choice(u.state,['planned','used']),confirmation:stamp(u.confirmation),standard_origin:u.standard_origin?{id:uuid(u.standard_origin.id),name:text(u.standard_origin.name,150),product_basis:text(u.standard_origin.product_basis,80)}:null})),
 document_versions:list(d.document_versions,100,v=>({id:uuid(v.id),document_id:uuid(v.document_id||v.id),name:text(v.name,200),type:choice(v.type,Object.keys(documentTypes)),source_kind:choice(v.source_kind||'business',['manufacturer','business','other_business','unknown']),source_label:text(v.source_label,300),url:url(v.url),document_date:text(v.document_date,80),language:text(v.language||'de',20),market:text(v.market||'DE',20),checked_at:text(v.checked_at,50),source_status:choice(v.source_status||'unverified',['archived','linked','missing','unverified','uploaded','historical']),visibility:visibility(v.visibility),file:file(v.file),text:text(v.text,6000)})),
 document_links:list(d.document_links,500,b=>({...bind(b),version_id:uuid(b.version_id)})),
 care:list(d.care,100,c=>({...bind(c),text:text(c.text,3000),source_version_id:uuid(c.source_version_id),source_kind:choice(c.source_kind||'business',['manufacturer','business','other_business']),source_label:text(c.source_label,300)})),
 maintenance:list(d.maintenance,100,m=>({...bind(m),reason:text(m.reason,1000),source_version_id:uuid(m.source_version_id),due_from:date(m.due_from),due_to:date(m.due_to),last_done:date(m.last_done),source_kind:choice(m.source_kind||'business',['manufacturer','business','other_business']),source_label:text(m.source_label,300),provider:text(m.provider,200)})),
 photos:list(d.photos,MAX_PHOTOS,p=>({id:uuid(p.id),area_id:uuid(p.area_id),section_id:uuid(p.section_id),step:choice(p.step,Object.keys(photoSteps)),caption:text(p.caption,1000),visibility:visibility(p.visibility),file:file(p.file,true)})),
 internal_notes:list(d.internal_notes||[],100,n=>({id:uuid(n.id),text:text(n.text,3000)})),migration:{origin:choice(d.migration?.origin||'new',['new','legacy','historical']),needs_review:d.migration?.needs_review===true,message:text(d.migration?.message,1000)},release:{kind:choice(d.release?.kind||'initial',['initial','correction','later_work']),reason:text(d.release?.reason,1000)}};
 if(!out.project.title.trim())fail('Bitte das Projekt benennen.');if(!out.sections.length||out.sections.filter(s=>s.kind==='initial').length!==1)fail('Genau ein ursprünglicher Arbeitsabschnitt ist erforderlich.');
 const sets={};for(const name of ['areas','sections','scopes','uses','document_versions','document_links','care','maintenance','photos','internal_notes']){const ids=out[name].map(x=>x.id);sets[name]=new Set(ids);if(ids.length!==sets[name].size)fail('Doppelte Kennung in '+name);}
 for(const s of out.sections){if(s.area_ids.some(a=>!sets.areas.has(a)))fail('Arbeitsabschnitt verweist auf eine fehlende Fläche.');if(s.performed_from&&s.performed_to&&s.performed_from>s.performed_to)fail('Zeitraum ist vertauscht.');}
 const scopes=new Set();for(const s of out.scopes){const key=[s.area_id,s.section_id,s.role].join('/');if(scopes.has(key))fail('Leistungsumfang ist doppelt.');scopes.add(key);}
 for(const name of ['scopes','uses','document_links','care','maintenance','photos'])for(const x of out[name]){if(!sets.areas.has(x.area_id)||!out.sections.some(s=>s.id===x.section_id&&s.area_ids.includes(x.area_id)))fail('Fläche oder Arbeitsabschnitt passt nicht.');for(const ref of x.dependencies||[]){const u=out.uses.find(u=>u.id===ref.usage_id);if(!u||u.area_id!==x.area_id||u.section_id!==x.section_id)fail('Unterlage oder Pflege verweist auf eine andere Fläche.');}}
 for(const b of [...out.document_links,...out.care,...out.maintenance])if(!sets.document_versions.has(b.version_id||b.source_version_id))fail('Dokumentfassung fehlt.');
 for(const u of out.uses){if(!scopes.has([u.area_id,u.section_id,u.role].join('/')))fail('Leistungsumfang fehlt.');if(!used(u)){u.state='planned';u.confirmation=null;}}
 for(const b of [...out.document_links,...out.care,...out.maintenance])if(b.confirmation?.basis!==bindingBasis(out,b))b.confirmation=null;
 for(const m of out.maintenance){if(m.due_from&&m.due_to&&m.due_from>m.due_to)fail('Wartungszeitraum ist vertauscht.');if(m.last_done&&m.due_from&&m.last_done>m.due_from)fail('Folgetermin liegt vor der letzten Wartung.');}
 for(const s of out.scopes)if(s.evidence_version_id&&!sets.document_versions.has(s.evidence_version_id))fail('Fremder Nachweis fehlt.');
 if(out.project.cover_photo_id&&!sets.photos.has(out.project.cover_photo_id))out.project.cover_photo_id='';
 // Never upgrade retrieval time into a document date or claim an upload is reviewed.
 for(const v of out.document_versions){if(v.file)v.source_status=v.source_status==='archived'?'archived':'uploaded';else if(!v.url&&!v.text)v.source_status='missing';else if(v.source_status==='archived')v.source_status='unverified';}
 return out;
}
export async function verifyAttachment(file,photo=false){try{if(photo)jpegInfo(file.data);else validateStaticPDF(file.data);const f=await fileInfo(file.data,file.name);if(f.size>(photo?412500:1048576))fail('Datei überschreitet die Pilotgrenze.');return f;}catch(e){fail(e.message);}}
export async function verifyFiles(d){let total=0;for(const item of [...d.photos,...d.document_versions])if(item.file){item.file=await verifyAttachment(item.file,Boolean(item.step));total+=item.file.size;}if(total>MAX_ARCHIVED_BYTES)fail('Archivierte Dateien überschreiten insgesamt 4 MB. Fotos bitte stärker komprimieren; Originale vorher separat sichern.');for(const group of ['document_links','care','maintenance'])for(const b of d[group]||[])if(b.confirmation?.basis!==bindingBasis(d,b))b.confirmation=null;return d;}
export function stampDeclarations(d,old,actor,at){for(const group of ['uses','document_links','care','maintenance'])for(const item of d[group]){if(!item.confirmation)continue;const previous=old?.[group]?.find(x=>x.id===item.id);const basis=group==='uses'?usageBasis(item):bindingBasis(d,item);if(previous?.confirmation?.basis===basis)item.confirmation=clone(previous.confirmation);else item.confirmation={basis,by:actor,at};}return d;}
export function sanitizeStandard(v){obj(v);return {id:uuid(v.id),name:text(v.name,150),trade:choice(v.trade,['tile','seamless']),roles:list(v.roles||[],30,r=>choice(r,Object.keys(roles))),products:list(v.products||[],40,x=>({role:choice(x.role,Object.keys(roles)),product:product(x.product)})),expected_photos:list(v.expected_photos||[],8,x=>choice(x,Object.keys(photoSteps))),notice:'Vorauswahl, kein technischer Kombinationsnachweis. Verwendung am Auftrag bestätigen.'};}
export function assertPublish(d,previous){if(!d.areas.length)fail('Mindestens eine Badfläche anlegen.');if(d.areas.some(a=>!a.name))fail('Alle Flächen benennen.');if(d.release.kind!=='initial'&&!d.release.reason)fail('Bitte den Grund der neuen Fassung dokumentieren.');if(previous&&d.release.kind==='initial')fail('Bitte Berichtigung oder spätere Arbeit auswählen.');
 if(d.release.kind==='correction'&&previous){for(const s of previous.sections){const next=d.sections.find(x=>x.id===s.id);if(!next||next.performed_from!==s.performed_from||next.performed_to!==s.performed_to)fail('Bei einer Berichtigung bleiben Ausführungsdaten unverändert.');}}
 if(d.release.kind==='later_work'&&previous){const priorIds=new Set(previous.sections.map(s=>s.id));const added=d.sections.filter(s=>!priorIds.has(s.id));if(!added.length||added.some(s=>!s.performed_from||s.kind==='initial'||!s.region))fail('Spätere Arbeit braucht einen neuen datierten Arbeitsabschnitt und eine Bereichsbeschreibung.');for(const section of previous.sections)if(canonical(section)!==canonical(d.sections.find(s=>s.id===section.id)))fail('Spätere Arbeit darf alte Arbeitsabschnitte nicht verändern.');for(const u of previous.uses){const next=d.uses.find(x=>x.id===u.id);if(!next||!used(next)||usageBasis(next)!==usageBasis(u))fail('Spätere Arbeit darf alte Materialverwendungen nicht überschreiben.');}for(const scope of previous.scopes){const next=d.scopes.find(x=>x.id===scope.id);if(!next||canonical(pick(next,['area_id','section_id','role','kind','company','note','evidence_version_id']))!==canonical(pick(scope,['area_id','section_id','role','kind','company','note','evidence_version_id'])))fail('Spätere Arbeit darf den früheren Leistungsumfang nicht ändern.');}}
}
export const badOps=new Set(['bad_summary','bad_get','bad_save','bad_publish','bad_read','bad_standard_save','bad_staff_create','bad_staff_revoke','bad_worker_get','bad_contribute','bad_review']);
export const badPublicOps=new Set(['bad_read','bad_worker_get','bad_contribute']);
export function validateBad(op,b){obj(b);if(op==='bad_summary')return {};if(op==='bad_read')return {token:token(b.token),number:b.number?version(b.number):0};if(op==='bad_worker_get')return {token:token(b.token)};if(op==='bad_contribute')obj(b.contribution);if(op==='bad_contribute')return {token:token(b.token),contribution:{id:uuid(b.contribution.id),area_id:uuid(b.contribution.area_id),section_id:uuid(b.contribution.section_id),type:choice(b.contribution.type,['photo','deviation','note']),text:text(b.contribution.text,3000),step:choice(b.contribution.step||'detail',Object.keys(photoSteps)),file:b.contribution.file?file(b.contribution.file,true):null}};
 const out={id:uuid(b.id)};if(op==='bad_get')return out;if(op==='bad_save'||op==='bad_publish'){if(!Number.isInteger(b.version)||b.version<0)fail();out.version=b.version;}
 if(op==='bad_save')out.draft=sanitizeDraft(b.draft);else if(op==='bad_publish'){out.request_id=uuid(b.request_id);if(b.confirm!==true)fail('Bitte die Kundenfreigabe ausdrücklich bestätigen.');}else if(op==='bad_standard_save')out.standard=sanitizeStandard(b.standard);else if(op==='bad_staff_create'){out.area_ids=list(b.area_ids,20,uuid);out.label=text(b.label,100);if(!out.label||!out.area_ids.length)fail('Name und zugeordnete Flächen fehlen.');}else if(op==='bad_staff_revoke')out.link_id=uuid(b.link_id);else if(op==='bad_review'){out.contribution_id=uuid(b.contribution_id);out.status=choice(b.status,['reviewed','declined']);}else fail();return out;
}
