import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {validate} from '../server/validation.mjs';
const actor='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',cid='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',pid='33333333-3333-4333-8333-333333333333';
const token='a'.repeat(64),key='b'.repeat(64),key2='c'.repeat(64),owner='d'.repeat(64);
test('construction → handover → owner invitations: real SQL isolation, revocation and retention',async()=>{
 const db=new PGlite();
 const rpc=async(op,args={},who=actor)=>(await db.query('select public.pp_api($1,$2::uuid,$3::jsonb) r',[op,who,JSON.stringify(args)])).rows[0].r;
 try{
 await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
 for(const f of ['schema.sql','collaboration.sql'])await db.exec(await readFile(new URL('../database/'+f,import.meta.url),'utf8'));
 await db.query('insert into pp_private.companies(id,profile) values($1,$2)',[cid,JSON.stringify({name:'Fliesenbetrieb'})]);
 await db.query('insert into pp_private.members values($1,$2)',[actor,cid]);
 await db.query('insert into pp_private.passes(id,company_id,number,token) values($1,$2,1,$3)',[pid,cid,token]);
 await db.exec('set role service_role');
 let p=await rpc('activate',{pass_id:pid,title:'Private Familie'});const id=p.id;
 await assert.rejects(()=>rpc('site_invite',{id,label:'Fremd',invite_hash:key},other),/PP_FORBIDDEN/);
 let t=await rpc('site_invite',{id,label:'Sanitär',invite_hash:key});
 let t2=await rpc('site_invite',{id,label:'Elektriker',invite_hash:key2});
 const cred={token,participant_id:t.participant_id,key_hash:key};
 await rpc('trade_note',{...cred,note:{text:'Noch nicht betreten',until:''}},null);
 await rpc('site_note',{id,note:{text:'Rosette offen lassen'} });
 let board=await rpc('scan',{token},null);
 assert.equal(board.phase,'construction');assert.equal(board.notes.length,2);
 assert.ok(!JSON.stringify(board).includes('Private Familie'));assert.equal(board.content,undefined);
 const businessNote=board.notes.find(n=>n.author==='Fliesenbetrieb');
 await assert.rejects(()=>rpc('trade_resolve',{...cred,note_id:businessNote.id},null),/PP_FORBIDDEN/);
 await rpc('site_resolve',{id,note_id:businessNote.id});
 assert.equal((await rpc('scan',{token},null)).notes.length,1);
 await assert.rejects(()=>rpc('trade_save',{...cred,participant_id:t2.participant_id,version:1,entry:{product:'Manipuliert'}},null),/PP_FORBIDDEN/);
 let saved=await rpc('trade_save',{...cred,version:1,entry:{product:'Armatur',note:'Reinigung mild'}},null);
 assert.equal(saved.version,2);
 await assert.rejects(()=>rpc('trade_save',{...cred,version:1,entry:{product:'Alt'}},null),/PP_CONFLICT/);
 await rpc('site_revoke',{id,participant_id:t2.participant_id});
 await assert.rejects(()=>rpc('trade_open',{token,participant_id:t2.participant_id,key_hash:key2},null),/PP_FORBIDDEN/);
 p=await rpc('owner_key',{id,version:p.version,key_hash:owner});
 p=await rpc('handover',{id,version:p.version});
 await assert.rejects(()=>rpc('trade_open',cred,null),/PP_FORBIDDEN/);
 await assert.rejects(()=>rpc('trade_note',{...cred,note:{text:'spät'}},null),/PP_FORBIDDEN/);
 await assert.rejects(()=>rpc('site_invite',{id,label:'Spät',invite_hash:key}),/PP_FORBIDDEN/);
 const customer=await rpc('scan',{token},null);assert.equal(customer.notes,undefined);
 assert.equal(customer.trades.find(x=>x.id===t.participant_id).entry.product,'Armatur');
 assert.equal((await db.query('select count(*)::int n from pp_private.site_notes')).rows[0].n,0);
 await assert.rejects(()=>rpc('owner_invite',{token,key_hash:key,label:'Fake',invite_hash:key},null),/PP_FORBIDDEN/);
 const renewed=await rpc('owner_invite',{token,key_hash:owner,label:'Sanitär',participant_id:t.participant_id,invite_hash:key2},null);
 assert.equal(renewed.participant_id,t.participant_id);
 await assert.rejects(()=>rpc('trade_open',cred,null),/PP_FORBIDDEN/);
 saved=await rpc('trade_open',{...cred,key_hash:key2},null);assert.equal(saved.entry.product,'Armatur');assert.deepEqual(saved.notes,[]);
 await assert.rejects(()=>rpc('trade_note',{...cred,key_hash:key2,note:{text:'Verboten'}},null),/PP_FORBIDDEN/);
 const later=await rpc('owner_invite',{token,key_hash:owner,label:'Spätere Firma',invite_hash:key},null);
 await rpc('trade_save',{token,key_hash:key,participant_id:later.participant_id,version:1,entry:{note:'Nur Kundenmappe'}},null);
 const business=await rpc('project',{id});assert.deepEqual(business.trades,[]);assert.ok(!JSON.stringify(business).includes('Nur Kundenmappe'));
 await rpc('owner_revoke',{token,key_hash:owner,participant_id:later.participant_id},null);
 await assert.rejects(()=>rpc('trade_open',{token,key_hash:key,participant_id:later.participant_id},null),/PP_FORBIDDEN/);
 assert.equal((await rpc('scan',{token},null)).trades.length,3);
 await assert.rejects(()=>rpc('owner_key',{id,version:p.version,key_hash:key}),/PP_FORBIDDEN/);
 await db.exec('reset role; set role anon;');
 await assert.rejects(()=>db.query('select * from pp_private.participants'),/permission denied/);
 await assert.rejects(()=>db.query("select pp_private.base_api('bootstrap',null,'{}')"),/permission denied/);
 }finally{await db.close();}
});
test('collaboration validation rejects tracking, invalid dates and forged ownership',()=>{
 const v=validate('trade_save',{token,key,participant_id:pid,version:1,entry:{product:'Armatur',owner:'attacker',url:''},actor});
 assert.equal(v.actor,undefined);assert.equal(v.entry.owner,undefined);
 assert.throws(()=>validate('trade_note',{token,key,participant_id:pid,note:{text:'x',until:'not a date'}}));
 assert.throws(()=>validate('trade_save',{token,key,participant_id:pid,version:1,entry:{url:'javascript:alert(1)'}}));
 assert.throws(()=>validate('site_invite',{id:pid,label:''}));
});
