import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Window} from 'happy-dom';
import {PGlite} from '@electric-sql/pglite';
import {createHandler} from '../server/api.mjs';
const operator='11111111-1111-4111-8111-111111111111',member='22222222-2222-4222-8222-222222222222';
const origin='https://projektpass.example';
const wait=async check=>{for(let i=0;i<150;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,20));}throw Error('UI did not reach expected state');};
test('operator → business onboarding → seamless handover; unlimited batches and legacy templates remain isolated',async()=>{
 const db=new PGlite();await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
 await db.exec(await readFile(new URL('../database/schema.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/operator.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/workflow.sql',import.meta.url),'utf8'));
 await db.query('insert into pp_private.operators(user_id) values($1)',[operator]);
 let authCreates=0;
 const json=(value,status=200)=>new Response(JSON.stringify(value),{status});
 const handle=createHandler(async(url,opts)=>{
   const b=opts.body?JSON.parse(opts.body):{};
   if(url.endsWith('/admin/users')){authCreates++;return json({id:member,email:b.email});}
   if(url.includes('/token')){const id=b.email==='owner@example.test'?operator:member;return json({access_token:id,expires_in:3600,user:{id,email:b.email}});}
   if(url.endsWith('/user'))return json({id:opts.headers.Authorization.slice(7)});
   if(url.endsWith('/logout'))return json({ok:true});
   const functionName=url.endsWith('/pp_flow')?'pp_flow':url.endsWith('/pp_control')?'pp_control':'pp_api';
   try{return json((await db.query(`select public.${functionName}($1,$2::uuid,$3::jsonb) result`,[b.op,b.actor,JSON.stringify(b.args)])).rows[0].result);}
   catch(e){return json({message:e.message},400);}
 });
 const win=new Window({url:origin+'/#login'});win.document.body.innerHTML='<div id="app"></div><dialog id="modal"></dialog><div id="notice"></div>';
 globalThis.window=win;globalThis.document=win.document;globalThis.location=win.location;globalThis.history=win.history;globalThis.FormData=win.FormData;globalThis.confirm=()=>true;
 let cookie='';globalThis.fetch=async(path,opts)=>{if(path==='/catalog.json')return json({version:1,checked_at:'2026-09-26',manufacturers:[{id:'testanbieter',name:'Testanbieter'},{id:'zweiter',name:'Zweiter Testanbieter'}],products:[{id:'testanbieter-test-pro',manufacturer_id:'testanbieter',name:'Testoberfläche Pro',kinds:['surface'],documents:[{name:'Testblatt',type:'Technisches Merkblatt',url:'https://example.test/TestPRO_TM.pdf',verification:'pdf'}]},{id:'testanbieter-test-ultra',manufacturer_id:'testanbieter',name:'Testoberfläche Ultra',kinds:['surface'],documents:[]},{id:'zweiter-test-primer',manufacturer_id:'zweiter',name:'Test Primer',kinds:['primer'],documents:[{url:'https://example.test/unconfirmed.pdf',verification:'source_link'}]}]});const r=await handle(new Request(origin+path,{...opts,headers:{...opts.headers,origin,cookie}}),{APP_ORIGIN:origin,SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_SECRET_KEY:'test_secret',SUPABASE_PUBLISHABLE_KEY:'test_public'});if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};
 const $=s=>win.document.querySelector(s),input=(s,value)=>{$(s).value=value;$(s).dispatchEvent(new win.Event('input',{bubbles:true}));},submit=s=>$(s).dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));
 try{
   await import('../public/app.mjs?operator-integration');await wait(()=>$('#login'));
   input('#email','owner@example.test');input('#password','Owner password 123');submit('#login');await wait(()=>$('#businesses'));
   assert.ok($('#app').textContent.includes('Betreiberverwaltung'));assert.ok($('a[href="#business-new"]'));
   win.location.hash='business-new';await wait(()=>$('#operator-business'));
   input('#name','Testbetrieb <A>');input('#email','member@example.test');submit('#operator-business');
   await wait(()=>$('#business-access'));
   assert.equal($('h1').textContent,'Testbetrieb <A>');assert.equal((await db.query('select count(*)::int n from pp_private.passes')).rows[0].n,20);
   submit('#business-access');await wait(()=>$('#access-link'));
   const link=$('#access-link').value;assert.match(link,/#access\/[a-f0-9]{64}$/);
   assert.ok($('#created-access').textContent.includes('keine E-Mail versendet'));
   assert.equal((await db.query('select kind from pp_private.access_invites')).rows[0].kind,'business');
   $('#logout').click();await wait(()=>$('#login'));
   win.location.hash=link.split('#')[1];await wait(()=>$('#access-setup'));
   assert.equal($('#setup-email').value,'member@example.test');assert.equal($('#setup-email').readOnly,true);
   input('#setup-password','Business password 123');input('#setup-repeat','different password');submit('#access-setup');
   await wait(()=>$('.form-message').textContent.includes('nicht überein'));assert.equal(authCreates,0);
   input('#setup-repeat','Business password 123');submit('#access-setup');await wait(()=>$('#settings'));
   assert.equal(authCreates,1);assert.ok(!win.location.href.includes('#access/'));assert.equal($('a[href="#admin"]'),null);
   assert.equal($('#trade').value,'');
   input('#trade','seamless');$('#trade').dispatchEvent(new win.Event('change'));
   assert.equal($('[data-care-kind="surface"]').hidden,false);assert.equal($('[data-care-kind="tile"]').hidden,true);
   input('#care-surface','Nur freigegebene Pflegemittel verwenden.');
   input('#favorite-surface','Testhersteller | Mikrozement 2K | Sand |');submit('#settings');await wait(()=>$('#search'));
   assert.equal((await db.query('select profile from pp_private.companies')).rows[0].profile.trade,'seamless');
   assert.ok($('#app').textContent.includes('Testbetrieb <A>'));
   win.location.hash='passes';await wait(()=>$('#add-passes'));
   $('#add-passes').click();input('#quantity','100');submit('#add-passes-form');
   await wait(()=>win.document.querySelectorAll('.pass-card').length===120);
   assert.ok($('#export-pass-links'));assert.equal((await db.query('select count(*)::int n from pp_private.passes')).rows[0].n,120);
   const pass=(await db.query('select id,token from pp_private.passes where number=120')).rows[0];
   win.location.hash='activate/'+pass.id;await wait(()=>$('#activate'));input('#title','Fugenloses Testbad');submit('#activate');await wait(()=>$('#edit'));
   assert.equal($('#tile-name'),null);assert.ok($('#surface-name'));assert.equal($('#care-surface').value,'Nur freigegebene Pflegemittel verwenden.');
   $('[data-favorite="surface:0"]').click();
   $('[data-open-catalog="surface"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));
   input('#catalog-manufacturer','testanbieter');$('#catalog-manufacturer').dispatchEvent(new win.Event('change'));input('#catalog-query','Testoberfläche');
   assert.equal(win.document.querySelectorAll('[data-catalog-pick]').length,2);
   $('[data-catalog-pick="testanbieter-test-pro"]').click();assert.equal($('#modal').open,false);assert.equal($('#surface-manufacturer').value,'Testanbieter');assert.equal($('#surface-name').value,'Testoberfläche Pro');assert.ok($('#documents').value.includes('TestPRO_TM.pdf'));
   const firstDocs=$('#documents').value;
   $('[data-open-catalog="surface"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));$('[data-catalog-pick="testanbieter-test-pro"]').click();assert.equal($('#documents').value,firstDocs);
   $('[data-open-catalog="primer"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));$('[data-catalog-pick="zweiter-test-primer"]').click();assert.equal($('#primer-name').value,'Test Primer');assert.ok(!$('#documents').value.includes('unconfirmed.pdf'));
   assert.equal($('.project-steps [aria-current]').textContent,'2. Bauphase');
   input('#surface-system_type','MicroTec');input('#application_area','Wand und Boden');input('#substrate','Vorbereiteter Estrich');
   input('#primer-name','Grundierung 1');input('#waterproofing-name','Abdichtung 2');input('#finish-name','Versiegelung 3');input('#finish-sheen','Matt');input('#silicone-name','Anschlussfuge 4');input('#customer_name','INTERNER KUNDE');
   $('#remember-standard').click();await wait(()=>$('#notice').textContent.startsWith('Standard gespeichert'));
   const savedStandard=(await db.query('select profile from pp_private.companies')).rows[0].profile.standards.seamless;
   assert.equal(savedStandard.surface.name,'Testoberfläche Pro');assert.equal(savedStandard.surface.color,'');assert.equal(savedStandard.surface.batch,'');assert.equal(savedStandard.photos,undefined);assert.ok(savedStandard.documents.length>0);
   $('#preview').click();await wait(()=>$('#handover'));
   assert.equal($('.project-steps [aria-current]').textContent,'3. Übergabe');
   assert.ok($('#app').textContent.includes('Meine Oberfläche'));assert.ok(!$('#app').textContent.includes('Meine Fliesen'));assert.ok(!$('#app').textContent.includes('INTERNER KUNDE'));
   $('[data-panel="joints"]').click();assert.ok($('#panel-joints').textContent.includes('Abdichtung 2'));assert.ok($('#panel-joints').textContent.includes('Matt'));
   $('#handover').click();await wait(()=>$('#copy-link'));
   // Changing the business default only affects future projects.
   win.location.hash='settings';await wait(()=>$('#settings'));input('#trade','tile');submit('#settings');await wait(()=>$('#search'));
   input('#search','Testoberfläche');assert.ok($('#projects').textContent.includes('Fugenloses Testbad'));
   win.location.hash='p/'+pass.token;await wait(()=>$('#owner-edit'));
   assert.ok($('#app').textContent.includes('Meine Oberfläche'));assert.ok($('#panel-tiles').textContent.includes('Vorbereiteter Estrich'));
   const project=(await db.query('select id,version,content from pp_private.projects')).rows[0];
   assert.equal(project.content.trade,'seamless');assert.equal(project.content.surface.manufacturer,'Testanbieter');
   const forged=await globalThis.fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:project.id,version:project.version,title:'Fugenloses Testbad',content:{...project.content,trade:'tile'},internal:{}})});
   assert.equal(forged.status,200);assert.equal((await forged.json()).content.trade,'seamless');
   assert.equal((await db.query('select handover_snapshot from pp_private.projects')).rows[0].handover_snapshot.content.trade,'seamless');
   win.location.hash='admin';await wait(()=>$('[role=alert]'));
   assert.ok($('[role=alert]').textContent.includes('nur für den Betreiber'));
   win.location.hash='login';await wait(()=>$('#login'));input('#email','owner@example.test');input('#password','Owner password 123');submit('#login');await wait(()=>$('#businesses'));
   assert.ok($('a[href="#business-new/me"]'));
   win.location.hash='business-new/me';await wait(()=>$('#operator-business'));input('#name','Eigener Fugenlosbetrieb');submit('#operator-business');await wait(()=>$('#settings'));
   input('#trade','seamless');submit('#settings');await wait(()=>$('#search'));
   assert.ok($('a[href="#admin"]'));assert.ok($('#app').textContent.includes('Eigener Fugenlosbetrieb'));
   assert.equal((await db.query('select count(*)::int n from pp_private.members where user_id=$1',[operator])).rows[0].n,1);
 }finally{await win.happyDOM.abort();await db.close();win.close();}
});
