import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Window} from 'happy-dom';
import {PGlite} from '@electric-sql/pglite';
import {createHandler} from '../server/api.mjs';
const operator='11111111-1111-4111-8111-111111111111',member='22222222-2222-4222-8222-222222222222';
const origin='https://projektpass.example';
const wait=async check=>{for(let i=0;i<150;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,20));}throw Error('UI did not reach expected state');};
test('operator → business onboarding → seamless handover; unlimited batches and legacy templates remain isolated',async()=>{
 const db=new PGlite();await db.exec('create role anon; create role authenticated; create role service_role bypassrls;');
 await db.exec(await readFile(new URL('../database/schema.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/operator.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../database/workflow.sql',import.meta.url),'utf8'));
 await db.query('insert into pp_private.operators(user_id) values($1)',[operator]);
 let authCreates=0;
 const json=(value,status=200)=>new Response(JSON.stringify(value),{status});
 const handle=createHandler(async(url,opts)=>{
   const b=opts.body?JSON.parse(opts.body):{};
   if(url.endsWith('/admin/users')){authCreates++;return json({id:member,email:b.email});}
   if(url.includes('/token')){const id=b.email==='owner@example.test'?operator:member;return json({access_token:id,expires_in:3600,user:{id,email:b.email}});}
   if(url.endsWith('/user'))return json({id:opts.headers.Authorization.slice(7)});
   if(url.endsWith('/logout'))return json({ok:true});
   const functionName=url.endsWith('/pp_flow')?'pp_flow':url.endsWith('/pp_control')?'pp_control':'pp_api';
   try{return json((await db.query(`select public.${functionName}($1,$2::uuid,$3::jsonb) result`,[b.op,b.actor,JSON.stringify(b.args)])).rows[0].result);}
   catch(e){return json({message:e.message},400);}
 });
 const win=new Window({url:origin+'/#login'});win.document.body.innerHTML='<div id="app"></div><dialog id="modal"></dialog><div id="notice"></div>';
 const baseCatalog=JSON.parse(await readFile(new URL('../public/catalog.json',import.meta.url),'utf8'));
 globalThis.window=win;globalThis.document=win.document;globalThis.location=win.location;globalThis.history=win.history;globalThis.FormData=win.FormData;globalThis.confirm=()=>true;
 let cookie='',saveOffline=false,bootstrapRequests=0;globalThis.fetch=async(path,opts)=>{if(path==='/api/bootstrap')bootstrapRequests++;if(path==='/api/save'&&saveOffline)throw Error('Test: keine Verbindung');if(path==='/catalog.json')return json({version:1,checked_at:'2026-09-26',manufacturers:[...baseCatalog.manufacturers,{id:'testanbieter',name:'Testanbieter'},{id:'zweiter',name:'Zweiter Testanbieter'}],products:[...baseCatalog.products,{id:'testanbieter-test-pro',manufacturer_id:'testanbieter',name:'Testoberfläche Pro',kinds:['surface'],documents:[{name:'Testblatt',type:'Technisches Merkblatt',url:'https://example.test/TestPRO_TM.pdf',verification:'pdf'}]},{id:'testanbieter-test-ultra',manufacturer_id:'testanbieter',name:'Testoberfläche Ultra',kinds:['surface'],documents:[]},{id:'zweiter-test-finish',manufacturer_id:'zweiter',name:'Test Versiegelung',kinds:['finish'],documents:[{url:'https://example.test/unconfirmed.pdf',verification:'source_link'}]}]});const r=await handle(new Request(origin+path,{...opts,headers:{...opts.headers,origin,cookie}}),{APP_ORIGIN:origin,SUPABASE_URL:'https://abcdefghijklmnopqrst.supabase.co',SUPABASE_SECRET_KEY:'test_secret',SUPABASE_PUBLISHABLE_KEY:'test_public'});if(r.headers.has('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];return r;};
 const $=s=>win.document.querySelector(s),input=(s,value)=>{$(s).value=value;$(s).dispatchEvent(new win.Event('input',{bubbles:true}));},submit=s=>$(s).dispatchEvent(new win.Event('submit',{bubbles:true,cancelable:true}));
 try{
   await import('../public/app.mjs?operator-integration');await wait(()=>$('#login'));
   input('#email','owner@example.test');input('#password','Owner password 123');submit('#login');await wait(()=>$('#businesses'));
   assert.equal(bootstrapRequests,0,'login result is reused without a second bootstrap');assert.ok($('#app').textContent.includes('Betreiberverwaltung'));assert.ok($('a[href="#business-new"]'));
   win.location.hash='business-new';await wait(()=>$('#operator-business'));assert.equal(bootstrapRequests,0,'navigation reuses the current business overview');
   input('#name','Testbetrieb <A>');input('#email','member@example.test');submit('#operator-business');
   await wait(()=>$('#business-access'));
   assert.equal($('h1').textContent,'Testbetrieb <A>');assert.equal((await db.query('select count(*)::int n from pp_private.passes')).rows[0].n,20);
   submit('#business-access');await wait(()=>$('#access-link'));
   const link=$('#access-link').value;assert.match(link,/#access\/[a-f0-9]{64}$/);
   assert.ok($('#created-access').textContent.includes('keine E-Mail versendet'));
   assert.equal((await db.query('select kind from pp_private.access_invites')).rows[0].kind,'business');
   $('#logout').click();await wait(()=>$('#login'));
   win.location.hash=link.split('#')[1];await wait(()=>$('#access-setup'));
   assert.equal($('#setup-email').value,'member@example.test');assert.equal($('#setup-email').readOnly,true);
   input('#setup-password','Business password 123');input('#setup-repeat','different password');submit('#access-setup');
   await wait(()=>$('.form-message').textContent.includes('nicht überein'));assert.equal(authCreates,0);
   input('#setup-repeat','Business password 123');submit('#access-setup');await wait(()=>$('#settings'));
   assert.equal(authCreates,1);assert.ok(!win.location.href.includes('#access/'));assert.equal($('a[href="#admin"]'),null);
   assert.equal($('#trade').value,'');
   input('#trade','seamless');$('#trade').dispatchEvent(new win.Event('change'));
   assert.equal($('[data-care-kind="surface"]').hidden,false);assert.equal($('[data-care-kind="tile"]').hidden,true);
   $('input[name="preferred-manufacturer"][value="Testanbieter"]').checked=true;
   input('#care-surface','Nur freigegebene Pflegemittel verwenden.');
   for(const [kind,maker,name,color] of [['waterproofing','PCI','Seccoral 1K',''],['surface','EPI','Quartz R','Sand']]){$('[data-favorite-new="'+kind+'"]').click();input('#favorite-maker',maker);input('#favorite-name',name);if(color)input('#favorite-color',color);$('[data-favorite-apply]').click();}submit('#settings');await wait(()=>$('#search'));
   assert.equal((await db.query('select profile from pp_private.companies')).rows[0].profile.trade,'seamless');
   assert.deepEqual((await db.query('select profile from pp_private.companies')).rows[0].profile.preferred_manufacturers,['Testanbieter']);
   assert.ok($('#app').textContent.includes('Testbetrieb <A>'));
   win.location.hash='passes';await wait(()=>$('#add-passes'));
   $('#add-passes').click();input('#quantity','100');submit('#add-passes-form');
   await wait(()=>win.document.querySelectorAll('.pass-card').length===120);
   assert.ok($('#export-pass-links'));assert.equal((await db.query('select count(*)::int n from pp_private.passes')).rows[0].n,120);
   const pass=(await db.query('select id,token from pp_private.passes where number=120')).rows[0];
   win.location.hash='activate/'+pass.id;await wait(()=>$('#activate'));input('#title','Fugenloses Testbad');submit('#activate');await wait(()=>$('#edit'));
   assert.equal(win.document.querySelectorAll('[data-editor-section]').length,4);
   assert.equal($('#primer-name'),null);
   assert.equal(win.document.querySelectorAll('details[data-material]').length,3);
   assert.ok($('[data-material="surface"] [data-material="finish"]'));
   assert.equal($('[data-material="finish"] .material-edit').open,false);
   assert.ok([...win.document.querySelectorAll('.manual-product')].every(s=>!s.open));
   assert.equal($('[data-editor-section="project"]').open,true);assert.ok([...win.document.querySelectorAll('[data-editor-section]:not([data-editor-section="project"])')].every(s=>!s.open));assert.equal($('#preview').hidden,true);assert.equal($('#editor-next').textContent,'Weiter: Materialien →');
   assert.ok($('.account-menu'));assert.equal($('.account-menu').open,false);
   assert.equal($('#documents').hidden,true);assert.ok($('[data-editor-section="materials"] .material-overview'));assert.equal(win.document.querySelectorAll('[data-editor-go]').length,4);
   assert.ok($('[data-material="waterproofing"] #waterproofing-photo-upload'));
   assert.equal($('[data-editor-section="files"] #waterproofing-photo-upload'),null);
   input('#surface-color','Automatisch gespeichert');
   await wait(()=>$('#save-status').textContent==='Gespeichert');
   assert.equal((await db.query('select content from pp_private.projects')).rows[0].content.surface.color,'Automatisch gespeichert');
   saveOffline=true;input('#surface-color','Bleibt bei Verbindungsfehler');
   await wait(()=>$('#save-status').textContent.includes('Nicht gespeichert'));
   assert.equal($('#surface-color').value,'Bleibt bei Verbindungsfehler');
   assert.equal((await db.query('select content from pp_private.projects')).rows[0].content.surface.color,'Automatisch gespeichert');
   saveOffline=false;win.dispatchEvent(new win.Event('online'));
   await wait(()=>$('#save-status').textContent==='Gespeichert');
   assert.equal((await db.query('select content from pp_private.projects')).rows[0].content.surface.color,'Bleibt bei Verbindungsfehler');
   input('#surface-color','Wird vor Navigation gespeichert');
   const autoId=(await db.query('select id from pp_private.projects')).rows[0].id;
   win.location.hash='home';await wait(()=>$('#search'));
   assert.equal((await db.query('select content from pp_private.projects')).rows[0].content.surface.color,'Wird vor Navigation gespeichert');
   win.location.hash='edit/'+autoId;await wait(()=>$('#edit'));
   assert.equal($('#save').hidden,true);
   input('#surface-color','');submit('#edit');await wait(()=>$('#save-status').textContent==='Gespeichert');
   $('#add-document').click();await wait(()=>$('#project-document'));
   input('#document-name','Eigene Pflegeanleitung | Sonderfläche');input('#document-url','https://example.test/manual-care.pdf');submit('#project-document');await wait(()=>!$('#modal').open);
   assert.ok($('#document-list').textContent.includes('Eigene Pflegeanleitung'));assert.ok($('[data-editor-summary="files"]').textContent.includes('1 Unterlage'));
   assert.equal(JSON.parse($('#documents').value)[0].name,'Eigene Pflegeanleitung | Sonderfläche');
   $('[data-remove-document="0"]').click();assert.ok(!$('#documents').value.includes('manual-care.pdf'));
   assert.equal($('#joint-materials'),null);assert.equal($('[data-material="silicone"] > summary strong').textContent,'Silikon / Anschlussfugen');
   $('[data-open-catalog="silicone"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));
   $('[data-catalog-pick="pci-silcofug-e"]').click();assert.equal($('#silicone-colors').children.length,28);assert.equal($('#silicone-color').value,'');
   input('#silicone-color','Sonderton Bestand');input('#silicone-name','Eigenes Silikon');
   assert.equal($('#silicone-colors').children.length,0);assert.equal($('#silicone-color').value,'Sonderton Bestand');
   assert.equal($('#tile-name'),null);assert.ok($('#surface-name'));assert.equal($('#care-surface').value,'Nur freigegebene Pflegemittel verwenden.');
   assert.equal($('[data-material-status="waterproofing"]').textContent,'Noch offen');
   $('[data-material-jump="surface"]').click();assert.equal($('#editor-next').textContent,'Weiter: Abdichtung →');
   $('#editor-next').click();assert.equal($('[data-material="waterproofing"]').open,true);assert.equal($('#editor-next').textContent,'Weiter: Silikon / Anschlussfugen →');
   $('#editor-next').click();assert.equal($('[data-material="silicone"]').open,true);assert.equal($('#editor-next').textContent,'Weiter: Fotos & Unterlagen →');
   $('[data-material-jump="waterproofing"]').click();assert.equal($('[data-material="waterproofing"]').open,true);
   $('[data-open-catalog="waterproofing"]').click();await wait(()=>$('#modal').open&&$('#catalog-manual'));
   $('#catalog-manual').click();assert.equal($('#modal').open,false);assert.equal($('[data-material="waterproofing"] .manual-product').open,true);assert.equal(win.document.activeElement.id,'waterproofing-manufacturer');
   assert.equal($('#waterproofing-color'),null);assert.equal($('#waterproofing-batch'),null);
   assert.equal($('#waterproofing-water-class').value,'');assert.equal($('#waterproofing-type').value,'');
   assert.match($('#waterproofing-documentation').textContent,/Fotos der Abdichtung \(empfohlen\)/);
   assert.ok(!$('[data-favorite="waterproofing:0"]').textContent.includes('grau'));
   $('[data-favorite="waterproofing:0"]').click();await wait(()=>!$('[data-favorite="waterproofing:0"]').disabled);
   assert.equal($('[data-material-status="waterproofing"]').textContent,'PCI Seccoral 1K');assert.equal($('[data-material-jump="waterproofing"]').classList.contains('is-missing'),false);assert.equal($('#waterproofing-name').value,'Seccoral 1K');assert.equal($('#waterproofing-water-class').value,'');
   submit('#edit');await wait(()=>$('.form-message').textContent.includes('Auf dem Server gespeichert'));
   const photo='data:image/jpeg;base64,/9j/AA==',photo2='data:image/jpeg;base64,/9j/BB==';
   const active=(await db.query('select id from pp_private.projects')).rows[0].id;
   assert.deepEqual((await db.query('select content from pp_private.projects')).rows[0].content.waterproofing_details,{water_class:'',type:'',photos:[]});
   // Seed previously uploaded JPEGs to exercise reopen, remove, save and snapshot persistence.
   await db.query("update pp_private.projects set content=jsonb_set(content,'{waterproofing_details}',$1::jsonb) where id=$2",[JSON.stringify({water_class:'W1-I',type:'sheet',photos:[photo,photo2]}),active]);
   win.location.hash='home';await wait(()=>$('#search'));win.location.hash='edit/'+active;await wait(()=>$('#edit'));
   assert.equal($('#waterproofing-water-class').value,'W1-I');assert.equal($('#waterproofing-type').value,'sheet');
   assert.equal(win.document.querySelectorAll('#waterproofing-photos img').length,2);
   $('[data-remove-waterproofing="1"]').click();assert.equal(win.document.querySelectorAll('#waterproofing-photos img').length,1);
   assert.equal($('#waterproofing-photo-upload').required,false);
   // Both upload controls enforce the combined limit before attempting image decoding.
   for(const selector of ['#waterproofing-photo-upload','#project-photos']){
    Object.defineProperty($(selector),'files',{configurable:true,value:Array(8).fill(new win.File(['image'],'test.jpg',{type:'image/jpeg'}))});
    await $(selector).onchange({target:$(selector)});
    assert.match($('#notice').textContent,/höchstens 8 Fotos insgesamt/);assert.equal($('#save').disabled,false);
   }
   assert.equal(win.document.querySelectorAll('#waterproofing-photos img').length,1);
   assert.equal($('#surface-colors').children.length,0);assert.equal($('#surface-color').value,'');
   assert.ok($('#surface-name').compareDocumentPosition($('#surface-color'))&win.Node.DOCUMENT_POSITION_FOLLOWING);
   input('#surface-manufacturer','EPI');input('#surface-name','Quartz R');
   assert.ok([...$('#surface-colors').children].some(o=>o.value==='Concrete (Blend)'));
   assert.equal($('#surface-color').value,'');assert.equal($('#surface-color-select').closest('.field').hidden,false);
   $('#surface-color-select').value='__custom__';$('#surface-color-select').dispatchEvent(new win.Event('change',{bubbles:true}));assert.equal($('#surface-color').getAttribute('list'),null);
   assert.equal($('label[for="surface-color"]').textContent,'Anderer Farbton');
   input('#surface-color','RAL 9001 / Sondermischung');
   $('#surface-color-select').value='__custom__';$('#surface-color-select').dispatchEvent(new win.Event('change',{bubbles:true}));assert.ok($('#surface-color-select'));
   assert.equal($('#surface-color').value,'RAL 9001 / Sondermischung');
   input('#surface-color','Sonderton <Sand> 123');input('#surface-manufacturer','.murface');input('#surface-name','MF Industrial');
   assert.ok([...$('#surface-colors').children].some(o=>o.value==='MF WHITE · B00'));
   assert.equal($('#surface-color').value,'Sonderton <Sand> 123');
   $('[data-favorite="surface:0"]').click();await wait(()=>!$('[data-favorite="surface:0"]').disabled);
   assert.equal($('#finish-name').value,'Corestone Sealer');assert.equal($('#finish-manufacturer').value,'EPI');
   assert.equal($('#finish-status').textContent,'Aus dem System vorausgefüllt');
   input('#finish-name','Meine Versiegelung');input('#finish-sheen','Matt');
   $('[data-favorite="surface:0"]').click();await wait(()=>!$('[data-favorite="surface:0"]').disabled);assert.equal($('#finish-name').value,'Meine Versiegelung');
   submit('#edit');await wait(()=>$('.form-message').textContent.includes('Auf dem Server gespeichert'));
   win.location.hash='home';await wait(()=>$('#search'));win.location.hash='edit/'+active;await wait(()=>$('#edit'));
   assert.equal($('#finish-name').value,'Meine Versiegelung');assert.equal($('#finish-sheen').value,'Matt');
   $('#clear-finish').click();assert.equal($('#finish-name').value,'');
   submit('#edit');await wait(()=>$('.form-message').textContent.includes('Auf dem Server gespeichert'));
   win.location.hash='home';await wait(()=>$('#search'));win.location.hash='edit/'+active;await wait(()=>$('#edit'));
   assert.equal($('#finish-name').value,'');assert.equal($('#finish-status').textContent,'Keine Angabe');
   $('#reset-finish').click();assert.equal($('#finish-name').value,'Corestone Sealer');
   assert.ok($('#surface-color-hint').textContent.includes('Corestone'));assert.equal($('#surface-color').value,'Sand');
   $('[data-open-catalog="surface"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));
   assert.equal($('#catalog-manufacturer').value,'__preferred');
   input('#catalog-manufacturer','lamurista');$('#catalog-manufacturer').dispatchEvent(new win.Event('change'));
   $('[data-catalog-pick="lamurista-hardrock-pro"]').click();
   assert.ok($('#documents').value.includes('Lamurista_HardrockPRO_TM.pdf'));assert.ok($('#documents').value.includes('Clean-Clear-01-25_WEB.pdf'));
   assert.equal($('#finish-name').value,'GoodLack wb');assert.equal($('#finish-manufacturer').value,'Lamurista');
   assert.equal($('#finish-sheen').value,'');assert.ok($('#documents').value.includes('Lamurista_GoodLack_wb_TM-Neu.pdf'));
   assert.ok([...$('#surface-colors').children].some(o=>o.value==='München'));assert.equal($('#surface-color').value,'');
   assert.equal($('#surface-system_type').value,'1K-MicroTEC-Putz');
   assert.ok($('#summary-surface').textContent.includes('Lamurista'));
   assert.ok($('[data-favorite="surface:0"]').closest('.favorite-shortcuts').textContent.includes('Schnellwahl'));
   $('#surface-color-select').value='München';$('#surface-color-select').dispatchEvent(new win.Event('input',{bubbles:true}));
   assert.equal($('#surface-color-select').value,'München');
   $('#surface-color-select').dispatchEvent(new win.Event('change',{bubbles:true}));
   assert.equal($('#surface-color').value,'München');assert.ok($('#summary-surface').textContent.includes('München'));
   submit('#edit');await wait(()=>$('.form-message').textContent.includes('Auf dem Server gespeichert'));
   win.location.hash='home';await wait(()=>$('#search'));win.location.hash='edit/'+active;await wait(()=>$('#edit'));
   assert.equal($('#surface-color-select').value,'München');assert.equal($('#surface-color').value,'München');

   assert.ok($('#surface-color-select'));
   $('#surface-color-select').value='__custom__';$('#surface-color-select').dispatchEvent(new win.Event('change',{bubbles:true}));input('#surface-color','NCS S 1502-Y / Sonderton');
   submit('#edit');await wait(()=>$('.form-message').textContent.includes('Auf dem Server gespeichert'));
   win.location.hash='home';await wait(()=>$('#search'));win.location.hash='edit/'+active;await wait(()=>$('#edit'));
   assert.equal($('#surface-color').value,'NCS S 1502-Y / Sonderton');assert.equal($('#surface-color').getAttribute('list'),null);
   assert.equal($('label[for="surface-color"]').textContent,'Anderer Farbton');
   $('#surface-color-select').value='__custom__';$('#surface-color-select').dispatchEvent(new win.Event('change',{bubbles:true}));assert.equal($('#surface-color').value,'NCS S 1502-Y / Sonderton');
   assert.ok($('#surface-color-select'));

   $('[data-open-catalog="surface"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));
   input('#catalog-manufacturer','testanbieter');$('#catalog-manufacturer').dispatchEvent(new win.Event('change'));input('#catalog-query','Testoberfläche');
   assert.equal(win.document.querySelectorAll('[data-catalog-pick]').length,2);
   $('[data-catalog-pick="testanbieter-test-pro"]').click();assert.equal($('#modal').open,false);assert.equal($('#surface-manufacturer').value,'Testanbieter');assert.equal($('#surface-name').value,'Testoberfläche Pro');assert.ok($('#documents').value.includes('TestPRO_TM.pdf'));
   assert.equal($('#finish-name').value,'');assert.equal($('#finish-manufacturer').value,'');
   assert.equal($('#surface-colors').children.length,0);assert.equal($('#surface-color-hint').hidden,true);assert.equal($('#surface-color').value,'');
   const firstDocs=$('#documents').value;
   $('[data-open-catalog="surface"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));$('[data-catalog-pick="testanbieter-test-pro"]').click();assert.equal($('#documents').value,firstDocs);
   $('[data-open-catalog="finish"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));input('#catalog-manufacturer','zweiter');$('#catalog-manufacturer').dispatchEvent(new win.Event('change'));$('[data-catalog-pick="zweiter-test-finish"]').click();assert.equal($('#finish-name').value,'Test Versiegelung');assert.ok(!$('#documents').value.includes('unconfirmed.pdf'));
   assert.equal($('.project-steps [aria-current]').textContent,'2. Bauphase');
   input('#surface-system_type','MicroTec');input('#application_area','Wände & Boden');$('#application_area').dispatchEvent(new win.Event('change'));input('#substrate','Vorbereiteter Estrich');
   const selectPreparation=(id,value)=>{input(id,value);$(id).dispatchEvent(new win.Event('change'));};
   selectPreparation('#prep-walls-base-kind','drywall');selectPreparation('#prep-walls-base-by','other');input('#prep-walls-base-company','Trockenbau Beispiel');
   $('[data-prep-add="walls"]').click();selectPreparation('#prep-walls-0-kind','filled');selectPreparation('#prep-walls-0-by','own');
   selectPreparation('#prep-floor-base-kind','screed');selectPreparation('#prep-floor-base-by','unknown');
   input('#waterproofing-name','Abdichtung 2');input('#waterproofing-water-class','W2-I');input('#waterproofing-type','compound');input('#finish-name','Versiegelung 3');input('#finish-sheen','Matt');input('#silicone-name','Anschlussfuge 4');input('#customer_name','INTERNER KUNDE');
   $('[data-save-library="surface"]').click();await wait(()=>$('#modal').open&&$('#library-product'));
   input('#library-url','https://example.test/project-product.pdf');input('#library-document-name','Passendes Produktblatt');submit('#library-product');
   await wait(()=>$('#notice').textContent.startsWith('Produkt im Betriebskatalog'));
   const ownProducts=(await db.query('select profile from pp_private.companies')).rows[0].profile.favorites.surface;
   assert.equal(ownProducts.length,2);assert.equal(ownProducts[1].name,'Testoberfläche Pro');assert.equal(ownProducts[1].documents[0].url,'https://example.test/project-product.pdf');assert.equal(ownProducts[1].batch,'');assert.ok($('#documents').value.includes('project-product.pdf'));
   $('[data-open-catalog="surface"]').click();await wait(()=>$('#modal').open&&$('#catalog-picker'));$('[data-catalog-pick="own-surface-1"]').click();assert.equal($('#surface-name').value,'Testoberfläche Pro');
   $('#nfc-link').click();assert.equal($('#nfc-url').value,origin+'/#p/'+pass.token);$('#modal').close();
   input('#surface-color','Sonderton <Sand> 123');
   $('#remember-standard').click();await wait(()=>$('#notice').textContent.startsWith('Standard gespeichert'));
   assert.ok($('#standard-summary').textContent.includes('Testoberfläche Pro'));assert.ok($('#standard-feedback').textContent.includes('Gespeichert'));
   const savedStandard=(await db.query('select profile from pp_private.companies')).rows[0].profile.standards.seamless;
   assert.equal(savedStandard.primer,undefined);assert.equal(savedStandard.finish.name,'Versiegelung 3');
   // Applying the usual build to an older incomplete project fills only the missing product.
   await db.query("update pp_private.projects set content=jsonb_set(content,'{waterproofing}','{}'::jsonb) where id=$1",[active]);
   win.location.hash='home';await wait(()=>$('#search'));win.location.hash='edit/'+active;await wait(()=>$('#edit'));
   assert.equal($('#waterproofing-name').value,'');assert.ok($('#use-standard'));
   $('#use-standard').click();await wait(()=>$('#waterproofing-name').value==='Abdichtung 2');
   assert.equal($('#surface-color').value,'Sonderton <Sand> 123');assert.equal($('#finish-name').value,'Versiegelung 3');assert.equal($('#use-standard').hidden,true);
   assert.equal($('#waterproofing-water-class').value,'W2-I');assert.equal(win.document.querySelectorAll('#waterproofing-photos img').length,1);
   assert.equal(savedStandard.preparation,undefined);assert.equal(savedStandard.waterproofing_details,undefined);assert.equal(savedStandard.waterproofing.color,'');
   assert.equal(savedStandard.surface.name,'Testoberfläche Pro');assert.equal(savedStandard.surface.color,'');assert.equal(savedStandard.surface.batch,'');assert.equal(savedStandard.photos,undefined);assert.ok(savedStandard.documents.length>0);
   assert.equal((await db.query('select content from pp_private.projects')).rows[0].content.surface.color,'Sonderton <Sand> 123');
   $('#preview').click();await wait(()=>$('#handover'));
   assert.ok($('#handover-review').textContent.includes('Vorbereiteter Estrich'));
   $('[data-review-edit=project]').click();await wait(()=>$('#edit'));assert.equal($('#edit').dataset.editorView,'detail');assert.equal($('#edit').dataset.activeStep,'project');assert.equal($('#surface-color').value,'Sonderton <Sand> 123');
   $('#preview').click();await wait(()=>$('#handover'));
   assert.equal($('.project-steps [aria-current]').textContent,'3. Übergabe');assert.ok($('#handover-review').textContent.includes('Versiegelung 3'));assert.equal($('#customer-preview').open,false);
   assert.ok($('#panel-care .care-documents a[href$="Clean-Clear-01-25_WEB.pdf"]'));
   assert.equal($('[data-panel=tiles] strong').textContent,'Materialien');
   $('[data-panel=documents]').click();assert.equal($('#panel-documents').hidden,false);assert.ok($('#panel-documents a'));
   $('[data-panel=care]').click();assert.equal($('#panel-documents').hidden,true);assert.equal($('#panel-care').hidden,false);assert.ok(!$('#app').textContent.includes('Meine Fliesen'));assert.ok(!$('#app').textContent.includes('INTERNER KUNDE'));
   $('[data-panel="tiles"]').click();assert.ok($('#panel-joints').textContent.includes('Abdichtung 2'));assert.ok($('#panel-joints').textContent.includes('Matt'));assert.ok($('#panel-joints').textContent.includes('W2-I'));assert.ok($('#panel-joints').textContent.includes('Dichtmasse'));assert.equal($('#panel-joints img').getAttribute('src'),photo);
   $('#handover').click();await wait(()=>$('#copy-link'));
   // Changing the business default only affects future projects.
   win.location.hash='settings';await wait(()=>$('#settings'));input('#trade','tile');submit('#settings');await wait(()=>$('#search'));
   input('#search','Testoberfläche');assert.ok($('#projects').textContent.includes('Fugenloses Testbad'));
   win.location.hash='p/'+pass.token;await wait(()=>$('#owner-edit'));
   assert.equal($('[data-panel=tiles] strong').textContent,'Materialien');
   $('[data-panel=documents]').click();assert.equal($('#panel-documents').hidden,false);assert.ok($('#panel-documents a'));
   $('[data-panel=care]').click();assert.equal($('#panel-documents').hidden,true);assert.equal($('#panel-care').hidden,false);assert.ok($('#panel-tiles').textContent.includes('Vorbereiteter Estrich'));
   assert.ok($('#panel-tiles').textContent.includes('Sonderton <Sand> 123'));
   assert.ok($('#panel-tiles').textContent.includes('Trockenbau Beispiel'));assert.ok($('#panel-tiles').textContent.includes('Ausgeführt durch: Testbetrieb <A>'));
   const handoverPreparation=(await db.query('select handover_snapshot from pp_private.projects')).rows[0].handover_snapshot.content.preparation;
   assert.equal(handoverPreparation[0].area,'walls');assert.equal(handoverPreparation[0].steps[0].by,'own');assert.equal(handoverPreparation[1].substrate.kind,'screed');
   const project=(await db.query('select id,version,content from pp_private.projects')).rows[0];
   assert.deepEqual(project.content.waterproofing_details,{water_class:'W2-I',type:'compound',photos:[photo]});
   assert.deepEqual((await db.query('select handover_snapshot from pp_private.projects')).rows[0].handover_snapshot.content.waterproofing_details,project.content.waterproofing_details);
   assert.equal(project.content.trade,'seamless');assert.equal(project.content.surface.manufacturer,'Testanbieter');
   const forged=await globalThis.fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:project.id,version:project.version,title:'Fugenloses Testbad',content:{...project.content,trade:'tile'},internal:{}})});
   assert.equal(forged.status,200);assert.equal((await forged.json()).content.trade,'seamless');
   assert.equal((await db.query('select handover_snapshot from pp_private.projects')).rows[0].handover_snapshot.content.trade,'seamless');
   win.location.hash='admin';await wait(()=>$('[role=alert]'));
   assert.ok($('[role=alert]').textContent.includes('nur für den Betreiber'));
   win.location.hash='login';await wait(()=>$('#login'));input('#email','owner@example.test');input('#password','Owner password 123');submit('#login');await wait(()=>$('#businesses'));
   assert.ok($('a[href="#business-new/me"]'));
   win.location.hash='business-new/me';await wait(()=>$('#operator-business'));input('#name','Eigener Fugenlosbetrieb');submit('#operator-business');await wait(()=>$('#settings'));
   input('#trade','seamless');submit('#settings');await wait(()=>$('#search'));
   assert.ok($('a[href="#admin"]'));assert.ok($('#app').textContent.includes('Eigener Fugenlosbetrieb'));
   assert.equal((await db.query('select count(*)::int n from pp_private.members where user_id=$1',[operator])).rows[0].n,1);
 }finally{await win.happyDOM.abort();await db.close();win.close();}
});
